// 用法: node scripts/gen-i18n.js
// 从 language.json 读取所有语言代码，基于已有人工翻译+通用词汇表批量生成翻译文件

const fs = require('fs')
const path = require('path')

const languageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../language.json'), 'utf-8'))

// 基础中文模板
const zhCN = JSON.parse(fs.readFileSync(path.join(__dirname, '../frontend/src/i18n/zh-CN.json'), 'utf-8'))

// 各语言的"nav"翻译 —— 导航栏是用户最常看到的
// 格式: { langCode: { nav: {...}, generate: { simple/medium/hard }, ... } }
// 对于没有完整翻译的语言，缺失的key会回退到中文

// 核心UI翻译：每个语言至少翻译nav和常用按钮
const i18nDir = path.join(__dirname, '../frontend/src/i18n')

const specific = {
  ja: JSON.parse(fs.readFileSync(path.join(i18nDir, 'ja.json'), 'utf-8')),
  ko: JSON.parse(fs.readFileSync(path.join(i18nDir, 'ko.json'), 'utf-8')),
  'zh-TW': JSON.parse(fs.readFileSync(path.join(i18nDir, 'zh-TW.json'), 'utf-8')),
  en: JSON.parse(fs.readFileSync(path.join(i18nDir, 'en.json'), 'utf-8')),
  fr: JSON.parse(fs.readFileSync(path.join(i18nDir, 'fr.json'), 'utf-8')),
}

// 各语言的导航和关键词条翻译
const navTranslations = {
  es: { nav: { generate: "Generar", history: "Historial", library: "Biblioteca", network: "Red" }, generate: { title: "Generar eBook", start: "Iniciar generación", generating: "Generando...", cancel: "Cancelar", simple: "Fácil", medium: "Medio", hard: "Difícil", description: "Describe el libro que deseas generar", difficulty: "Dificultad", wordCount: "Palabras objetivo", chapterCount: "Número de capítulos", style: "Estilo", placeholder: "Ej: Un libro introductorio sobre inteligencia artificial para principiantes...", completed: "¡Generación completada!", preparing: "Preparando...", error: "Error", cancelled: "Cancelado", reconnecting: "Reconectando...", reconnectFailed: "Reconexión fallida", outlinePreview: "Vista previa del esquema", progress: "Progreso de generación", taskRunning: "Tarea #{id} · Cambiar de página no interrumpe", }, history: { title: "Historial de generación", newGenerate: "Nueva generación", all: "Todo", pending: "En curso", completed: "Completado", failed: "Fallido", deleted: "Eliminado", noRecords: "Sin historial", goGenerate: "Generar un eBook", viewProgress: "Ver progreso", cancel: "Cancelar", read: "Leer", regenerate: "Regenerar", delete: "Eliminar", createdAt: "Creado", completedAt: "Completado", difficulty: "Dificultad", wordCount: "Palabras objetivo", chapters: "capítulos", realtimeProgress: "Progreso en tiempo real", processing: "Procesando...", chapter: "Capítulo {current}", totalChapters: "Total {total} capítulos", outline: "Esquema", error: "Error", confirmDelete: "¿Está seguro de que desea eliminar este registro? Esta acción no se puede deshacer.", confirmDeleteTitle: "Eliminar registro" }, library: { title: "Mi biblioteca", settings: "Configuración", userInfo: "Información del usuario", userId: "ID de usuario", booksDir: "Ubicación de guardado", save: "Guardar", currentDir: "Ubicación actual", all: "Todo", local: "Local", p2p: "Fuente P2P", noBooks: "Sin libros, ¡genera uno!", read: "Leer", delete: "Eliminar", chapters: "{count} capítulos", confirmDelete: "¿Está seguro de que desea eliminar este libro? Los archivos locales también se eliminarán. Esta acción no se puede deshacer.", confirmDeleteTitle: "Eliminar libro", saved: "Ubicación de guardado actualizada" }, network: { title: "Red P2P", myInfo: "Info de mi nodo", userId: "ID de usuario", ip: "Dirección IP", bookCount: "Número de libros", nodes: "Nodos en línea", noNodes: "Sin otros nodos en línea", books: "Libros compartidos", noBooks: "Sin libros compartidos", download: "Descargar", downloading: "Descargando...", downloadSuccess: "¡Libro descargado exitosamente!", confirmDownload: "¿Desea descargar este libro?", local: "Local", p2p: "P2P" }, reader: { loading: "Cargando...", notFound: "Libro no encontrado", back: "Volver a la biblioteca" }, modal: { confirm: "Confirmar", cancel: "Cancelar" } },
  'es-419': 'es', 'es-MX': 'es',
  de: { nav: { generate: "Erstellen", history: "Verlauf", library: "Bibliothek", network: "Netzwerk" }, generate: { title: "eBook erstellen", start: "Erstellung starten", generating: "Erstellung...", cancel: "Abbrechen", simple: "Einfach", medium: "Mittel", hard: "Schwierig", description: "Beschreiben Sie das gewünschte Buch", difficulty: "Schwierigkeit", wordCount: "Zielwortzahl", chapterCount: "Kapitelanzahl", style: "Stil", placeholder: "z.B. Ein Einsteigerbuch über Künstliche Intelligenz...", completed: "Erstellung abgeschlossen!", preparing: "Vorbereitung...", error: "Fehler", cancelled: "Abgebrochen", reconnecting: "Wiederverbinden...", reconnectFailed: "Wiederverbindung fehlgeschlagen", outlinePreview: "Gliederungsvorschau", progress: "Erstellungsfortschritt", taskRunning: "Aufgabe #{id} · Seitenwechsel unterbricht nicht", }, history: { title: "Erstellungsverlauf", newGenerate: "Neue Erstellung", all: "Alle", pending: "In Bearbeitung", completed: "Abgeschlossen", failed: "Fehlgeschlagen", deleted: "Gelöscht", noRecords: "Kein Verlauf vorhanden", goGenerate: "eBook erstellen", viewProgress: "Fortschritt anzeigen", cancel: "Abbrechen", read: "Lesen", regenerate: "Neu erstellen", delete: "Löschen", createdAt: "Erstellt", completedAt: "Abgeschlossen", difficulty: "Schwierigkeit", wordCount: "Zielwörter", chapters: "Kapitel", realtimeProgress: "Echtzeit-Fortschritt", processing: "Verarbeitung...", chapter: "Kapitel {current}", totalChapters: "Gesamt {total} Kapitel", outline: "Gliederung", error: "Fehler", confirmDelete: "Möchten Sie diesen Eintrag wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.", confirmDeleteTitle: "Eintrag löschen" }, library: { title: "Meine Bibliothek", settings: "Einstellungen", userInfo: "Benutzerinformationen", userId: "Benutzer-ID", booksDir: "Speicherort", save: "Speichern", currentDir: "Aktueller Speicherort", all: "Alle", local: "Lokal", p2p: "P2P-Quelle", noBooks: "Keine Bücher vorhanden, erstellen Sie eines!", read: "Lesen", delete: "Löschen", chapters: "{count} Kapitel", confirmDelete: "Möchten Sie dieses Buch wirklich löschen? Lokale Dateien werden ebenfalls gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.", confirmDeleteTitle: "Buch löschen", saved: "Speicherort aktualisiert" }, network: { title: "P2P-Netzwerk", myInfo: "Meine Knoteninformationen", userId: "Benutzer-ID", ip: "IP-Adresse", bookCount: "Buchanzahl", nodes: "Online-Knoten", noNodes: "Keine weiteren Online-Knoten", books: "Geteilte Bücher", noBooks: "Keine geteilten Bücher", download: "Herunterladen", downloading: "Wird heruntergeladen...", downloadSuccess: "Buch erfolgreich heruntergeladen!", confirmDownload: "Möchten Sie dieses Buch herunterladen?", local: "Lokal", p2p: "P2P" }, reader: { loading: "Laden...", notFound: "Buch nicht gefunden", back: "Zurück zur Bibliothek" }, modal: { confirm: "Bestätigen", cancel: "Abbrechen" } },
  it: { nav: { generate: "Genera", history: "Cronologia", library: "Libreria", network: "Rete" }, generate: { title: "Genera eBook", start: "Inizia generazione", generating: "Generazione...", cancel: "Annulla", simple: "Facile", medium: "Medio", hard: "Difficile", description: "Descrivi il libro che vuoi generare", difficulty: "Difficoltà", wordCount: "Parole obiettivo", chapterCount: "Numero di capitoli", style: "Stile", placeholder: "es: Un libro introduttivo sull'intelligenza artificiale per principianti...", completed: "Generazione completata!", preparing: "Preparazione...", error: "Errore", cancelled: "Annullato", reconnecting: "Riconnessione...", reconnectFailed: "Riconnessione fallita", outlinePreview: "Anteprima sommario", progress: "Progresso generazione", taskRunning: "Attività #{id} · Cambiare pagina non interrompe" }, history: { title: "Cronologia generazione", newGenerate: "Nuova generazione", all: "Tutto", pending: "In corso", completed: "Completato", failed: "Fallito", deleted: "Eliminato", noRecords: "Nessuna cronologia", goGenerate: "Genera un eBook", viewProgress: "Vedi progresso", cancel: "Annulla", read: "Leggi", regenerate: "Rigenera", delete: "Elimina", createdAt: "Creato", completedAt: "Completato", difficulty: "Difficoltà", wordCount: "Parole obiettivo", chapters: "capitoli", realtimeProgress: "Progresso in tempo reale", processing: "Elaborazione...", chapter: "Capitolo {current}", totalChapters: "Totale {total} capitoli", outline: "Sommario", error: "Errore", confirmDelete: "Sei sicuro di voler eliminare questo record? Questa azione è irreversibile.", confirmDeleteTitle: "Elimina record" }, library: { title: "La mia libreria", settings: "Impostazioni", userInfo: "Info utente", userId: "ID utente", booksDir: "Posizione salvataggio", save: "Salva", currentDir: "Posizione attuale", all: "Tutto", local: "Locale", p2p: "Fonte P2P", noBooks: "Nessun libro, generane uno!", read: "Leggi", delete: "Elimina", chapters: "{count} capitoli", confirmDelete: "Sei sicuro di voler eliminare questo libro? Anche i file locali saranno eliminati. Azione irreversibile.", confirmDeleteTitle: "Elimina libro", saved: "Posizione salvataggio aggiornata" }, network: { title: "Rete P2P", myInfo: "Info mio nodo", userId: "ID utente", ip: "Indirizzo IP", bookCount: "Numero libri", nodes: "Nodi online", noNodes: "Nessun altro nodo online", books: "Libri condivisi", noBooks: "Nessun libro condiviso", download: "Scarica", downloading: "Scaricamento...", downloadSuccess: "Libro scaricato con successo!", confirmDownload: "Vuoi scaricare questo libro?", local: "Locale", p2p: "P2P" }, reader: { loading: "Caricamento...", notFound: "Libro non trovato", back: "Torna alla libreria" }, modal: { confirm: "Conferma", cancel: "Annulla" } },
  'pt-BR': { nav: { generate: "Gerar", history: "Histórico", library: "Biblioteca", network: "Rede" }, generate: { title: "Gerar eBook", start: "Iniciar geração", generating: "Gerando...", cancel: "Cancelar", simple: "Fácil", medium: "Médio", hard: "Difícil", description: "Descreva o livro que deseja gerar", difficulty: "Dificuldade", wordCount: "Quantidade de palavras", chapterCount: "Número de capítulos", style: "Estilo", placeholder: "Ex: Um livro introdutório sobre inteligência artificial para iniciantes...", completed: "Geração concluída!", preparing: "Preparando...", error: "Erro", cancelled: "Cancelado", reconnecting: "Reconectando...", reconnectFailed: "Falha na reconexão", outlinePreview: "Prévia do sumário", progress: "Progresso da geração", taskRunning: "Tarefa #{id} · Trocar página não interrompe" }, history: { title: "Histórico de geração", newGenerate: "Nova geração", all: "Tudo", pending: "Em andamento", completed: "Concluído", failed: "Falhou", deleted: "Excluído", noRecords: "Sem histórico", goGenerate: "Gerar um eBook", viewProgress: "Ver progresso", cancel: "Cancelar", read: "Ler", regenerate: "Regenerar", delete: "Excluir", createdAt: "Criado em", completedAt: "Concluído em", difficulty: "Dificuldade", wordCount: "Palavras alvo", chapters: "capítulos", realtimeProgress: "Progresso em tempo real", processing: "Processando...", chapter: "Capítulo {current}", totalChapters: "Total {total} capítulos", outline: "Sumário", error: "Erro", confirmDelete: "Tem certeza de que deseja excluir este registro? Esta ação não pode ser desfeita.", confirmDeleteTitle: "Excluir registro" }, library: { title: "Minha biblioteca", settings: "Configurações", userInfo: "Informações do usuário", userId: "ID do usuário", booksDir: "Local de salvamento", save: "Salvar", currentDir: "Local atual", all: "Tudo", local: "Local", p2p: "Fonte P2P", noBooks: "Sem livros, gere um!", read: "Ler", delete: "Excluir", chapters: "{count} capítulos", confirmDelete: "Tem certeza de que deseja excluir este livro? Os arquivos locais também serão excluídos. Ação irreversível.", confirmDeleteTitle: "Excluir livro", saved: "Local de salvamento atualizado" }, network: { title: "Rede P2P", myInfo: "Info do meu nó", userId: "ID do usuário", ip: "Endereço IP", bookCount: "Número de livros", nodes: "Nós online", noNodes: "Sem outros nós online", books: "Livros compartilhados", noBooks: "Sem livros compartilhados", download: "Baixar", downloading: "Baixando...", downloadSuccess: "Livro baixado com sucesso!", confirmDownload: "Deseja baixar este livro?", local: "Local", p2p: "P2P" }, reader: { loading: "Carregando...", notFound: "Livro não encontrado", back: "Voltar à biblioteca" }, modal: { confirm: "Confirmar", cancel: "Cancelar" } },
  'pt-PT': 'pt-BR',
  ru: { nav: { generate: "Создать", history: "История", library: "Библиотека", network: "Сеть" }, generate: { title: "Создать электронную книгу", start: "Начать создание", generating: "Создание...", cancel: "Отмена", simple: "Простой", medium: "Средний", hard: "Сложный", description: "Опишите книгу, которую хотите создать", difficulty: "Сложность", wordCount: "Целевое количество слов", chapterCount: "Количество глав", style: "Стиль", placeholder: "Например: Вводная книга по искусственному интеллекту для начинающих...", completed: "Создание завершено!", preparing: "Подготовка...", error: "Ошибка", cancelled: "Отменено", reconnecting: "Переподключение...", reconnectFailed: "Ошибка переподключения", outlinePreview: "Предпросмотр оглавления", progress: "Ход создания", taskRunning: "Задача #{id} · Переключение страниц не прерывает создание" }, history: { title: "История создания", newGenerate: "Новое создание", all: "Все", pending: "В процессе", completed: "Завершено", failed: "Ошибка", deleted: "Удалено", noRecords: "Нет записей", goGenerate: "Создать электронную книгу", viewProgress: "Посмотреть ход", cancel: "Отмена", read: "Читать", regenerate: "Пересоздать", delete: "Удалить", createdAt: "Создано", completedAt: "Завершено", difficulty: "Сложность", wordCount: "Целевые слова", chapters: "глав", realtimeProgress: "Ход в реальном времени", processing: "Обработка...", chapter: "Глава {current}", totalChapters: "Всего {total} глав", outline: "Оглавление", error: "Ошибка", confirmDelete: "Вы уверены, что хотите удалить эту запись? Это действие нельзя отменить.", confirmDeleteTitle: "Удалить запись" }, library: { title: "Моя библиотека", settings: "Настройки", userInfo: "Информация о пользователе", userId: "ID пользователя", booksDir: "Место сохранения", save: "Сохранить", currentDir: "Текущее место", all: "Все", local: "Локальные", p2p: "P2P источник", noBooks: "Нет книг, создайте одну!", read: "Читать", delete: "Удалить", chapters: "{count} глав", confirmDelete: "Вы уверены, что хотите удалить эту книгу? Локальные файлы также будут удалены. Это действие нельзя отменить.", confirmDeleteTitle: "Удалить книгу", saved: "Место сохранения обновлено" }, network: { title: "P2P сеть", myInfo: "Информация о моём узле", userId: "ID пользователя", ip: "IP-адрес", bookCount: "Количество книг", nodes: "Узлы в сети", noNodes: "Нет других узлов в сети", books: "Общие книги", noBooks: "Нет общих книг", download: "Скачать", downloading: "Загрузка...", downloadSuccess: "Книга успешно скачана!", confirmDownload: "Хотите скачать эту книгу?", local: "Локальные", p2p: "P2P" }, reader: { loading: "Загрузка...", notFound: "Книга не найдена", back: "Вернуться в библиотеку" }, modal: { confirm: "Подтвердить", cancel: "Отмена" } },
  ar: { nav: { generate: "إنشاء", history: "السجل", library: "المكتبة", network: "الشبكة" }, generate: { title: "إنشاء كتاب إلكتروني", start: "بدء الإنشاء", generating: "جارٍ الإنشاء...", cancel: "إلغاء", simple: "سهل", medium: "متوسط", hard: "صعب", description: "صِف الكتاب الذي تريد إنشاءه", difficulty: "الصعوبة", wordCount: "العدد المستهدف من الكلمات", chapterCount: "عدد الفصول", style: "الأسلوب", placeholder: "مثال: كتاب تمهيدي عن الذكاء الاصطناعي للمبتدئين...", completed: "تم الإنشاء!", preparing: "جارٍ التحضير...", error: "خطأ", cancelled: "ملغى", reconnecting: "جارٍ إعادة الاتصال...", reconnectFailed: "فشل إعادة الاتصال", outlinePreview: "معاينة المخطط", progress: "تقدم الإنشاء", taskRunning: "المهمة #{id} · التبديل بين الصفحات لا يقطع" }, history: { title: "سجل الإنشاء", newGenerate: "إنشاء جديد", all: "الكل", pending: "قيد التنفيذ", completed: "مكتمل", failed: "فشل", deleted: "محذوف", noRecords: "لا سجلات", goGenerate: "إنشاء كتاب إلكتروني", viewProgress: "عرض التقدم", cancel: "إلغاء", read: "قراءة", regenerate: "إعادة الإنشاء", delete: "حذف", createdAt: "تاريخ الإنشاء", completedAt: "تاريخ الإكمال", difficulty: "الصعوبة", wordCount: "الكلمات المستهدفة", chapters: "فصول", realtimeProgress: "التقدم في الوقت الفعلي", processing: "جارٍ المعالجة...", chapter: "الفصل {current}", totalChapters: "إجمالي {total} فصول", outline: "المخطط", error: "خطأ", confirmDelete: "هل أنت متأكد من حذف هذا السجل؟ لا يمكن التراجع عن هذا الإجراء.", confirmDeleteTitle: "حذف السجل" }, library: { title: "مكتبتي", settings: "الإعدادات", userInfo: "معلومات المستخدم", userId: "معرف المستخدم", booksDir: "موقع حفظ الكتب", save: "حفظ", currentDir: "الموقع الحالي", all: "الكل", local: "محلي", p2p: "مصدر P2P", noBooks: "لا كتب، أنشئ واحدة!", read: "قراءة", delete: "حذف", chapters: "{count} فصول", confirmDelete: "هل أنت متأكد من حذف هذا الكتاب؟ سيتم حذف الملفات المحلية أيضاً. لا يمكن التراجع عن هذا الإجراء.", confirmDeleteTitle: "حذف الكتاب", saved: "تم تحديث موقع الحفظ" }, network: { title: "شبكة P2P", myInfo: "معلومات العقدة", userId: "معرف المستخدم", ip: "عنوان IP", bookCount: "عدد الكتب", nodes: "العقد المتصلة", noNodes: "لا عقد متصلة أخرى", books: "الكتب المشتركة", noBooks: "لا كتب مشتركة", download: "تنزيل", downloading: "جارٍ التنزيل...", downloadSuccess: "تم تنزيل الكتاب بنجاح!", confirmDownload: "هل تريد تنزيل هذا الكتاب؟", local: "محلي", p2p: "P2P" }, reader: { loading: "جارٍ التحميل...", notFound: "الكتاب غير موجود", back: "العودة إلى المكتبة" }, modal: { confirm: "تأكيد", cancel: "إلغاء" } },
  'ar-EG': 'ar',
  hi: { nav: { generate: "बनाएँ", history: "इतिहास", library: "पुस्तकालय", network: "नेटवर्क" }, generate: { title: "ईबुक बनाएँ", start: "निर्माण शुरू करें", generating: "बना रहा है...", cancel: "रद्द करें", simple: "आसान", medium: "मध्यम", hard: "कठिन", description: "जो किताब बनाना चाहते हैं उसका वर्णन करें", difficulty: "कठिनाई", wordCount: "लक्ष्य शब्द संख्या", chapterCount: "अध्याय संख्या", style: "शैली", placeholder: "उदाहरण: कृत्रिम बुद्धिमत्ता पर शुरुआती किताब...", completed: "निर्माण पूर्ण!", preparing: "तैयारी...", error: "त्रुटि", cancelled: "रद्द किया गया", reconnecting: "पुनः कनेक्ट हो रहा है...", reconnectFailed: "पुनः कनेक्ट विफल", outlinePreview: "रूपरेखा पूर्वावलोकन", progress: "निर्माण प्रगति", taskRunning: "कार्य #{id} · पेज बदलने से निर्माण नहीं रुकता" }, history: { title: "निर्माण इतिहास", newGenerate: "नया निर्माण", all: "सभी", pending: "जारी", completed: "पूर्ण", failed: "विफल", deleted: "हटाए गए", noRecords: "कोई रिकॉर्ड नहीं", goGenerate: "ईबुक बनाएँ", viewProgress: "प्रगति देखें", cancel: "रद्द करें", read: "पढ़ें", regenerate: "फिर से बनाएँ", delete: "हटाएँ", createdAt: "बनाया गया", completedAt: "पूरा हुआ", difficulty: "कठिनाई", wordCount: "लक्ष्य शब्द", chapters: "अध्याय", realtimeProgress: "रियल-टाइम प्रगति", processing: "प्रसंस्करण...", chapter: "अध्याय {current}", totalChapters: "कुल {total} अध्याय", outline: "रूपरेखा", error: "त्रुटि", confirmDelete: "क्या आप इस रिकॉर्ड को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।", confirmDeleteTitle: "रिकॉर्ड हटाएँ" }, library: { title: "मेरा पुस्तकालय", settings: "सेटिंग्स", userInfo: "उपयोगकर्ता जानकारी", userId: "उपयोगकर्ता ID", booksDir: "किताबें सहेजने का स्थान", save: "सहेजें", currentDir: "वर्तमान स्थान", all: "सभी", local: "स्थानीय", p2p: "P2P स्रोत", noBooks: "कोई किताब नहीं, एक बनाएँ!", read: "पढ़ें", delete: "हटाएँ", chapters: "{count} अध्याय", confirmDelete: "क्या आप इस किताब को हटाना चाहते हैं? स्थानीय फ़ाइलें भी हटा दी जाएँगी। यह क्रिया पूर्ववत नहीं की जा सकती।", confirmDeleteTitle: "किताब हटाएँ", saved: "सहेजने का स्थान अपडेट किया गया" }, network: { title: "P2P नेटवर्क", myInfo: "मेरी नोड जानकारी", userId: "उपयोगकर्ता ID", ip: "IP पता", bookCount: "किताबों की संख्या", nodes: "ऑनलाइन नोड्स", noNodes: "कोई अन्य ऑनलाइन नोड नहीं", books: "साझा किताबें", noBooks: "कोई साझा किताबें नहीं", download: "डाउनलोड", downloading: "डाउनलोड हो रहा है...", downloadSuccess: "किताब सफलतापूर्वक डाउनलोड हुई!", confirmDownload: "क्या आप यह किताब डाउनलोड करना चाहते हैं?", local: "स्थानीय", p2p: "P2P" }, reader: { loading: "लोड हो रहा है...", notFound: "किताब नहीं मिली", back: "पुस्तकालय में वापस" }, modal: { confirm: "पुष्टि करें", cancel: "रद्द करें" } },
  th: { nav: { generate: "สร้าง", history: "ประวัติ", library: "ห้องสมุด", network: "เครือข่าย" }, generate: { title: "สร้างอีบุ๊ก", start: "เริ่มสร้าง", generating: "กำลังสร้าง...", cancel: "ยกเลิก", simple: "ง่าย", medium: "ปานกลาง", hard: "ยาก", description: "อธิบายหนังสือที่คุณต้องการสร้าง", difficulty: "ความยาก", wordCount: "จำนวนคำเป้าหมาย", chapterCount: "จำนวนบท", style: "สไตล์", placeholder: "เช่น หนังสือแนะนำปัญญาประดิษฐ์สำหรับผู้เริ่มต้น...", completed: "สร้างเสร็จ!", preparing: "กำลังเตรียม...", error: "ข้อผิดพลาด", cancelled: "ยกเลิกแล้ว", reconnecting: "กำลังเชื่อมต่อใหม่...", reconnectFailed: "การเชื่อมต่อใหม่ล้มเหลว", outlinePreview: "ตัวอย่างโครงร่าง", progress: "ความคืบหน้า", taskRunning: "งาน #{id} · เปลี่ยนหน้าไม่กระทบการสร้าง" }, history: { title: "ประวัติการสร้าง", newGenerate: "สร้างใหม่", all: "ทั้งหมด", pending: "กำลังดำเนินการ", completed: "เสร็จสมบูรณ์", failed: "ล้มเหลว", deleted: "ลบแล้ว", noRecords: "ไม่มีประวัติ", goGenerate: "สร้างอีบุ๊ก", viewProgress: "ดูความคืบหน้า", cancel: "ยกเลิก", read: "อ่าน", regenerate: "สร้างใหม่", delete: "ลบ", createdAt: "สร้างเมื่อ", completedAt: "เสร็จเมื่อ", difficulty: "ความยาก", wordCount: "จำนวนคำเป้าหมาย", chapters: "บท", realtimeProgress: "ความคืบหน้าแบบเรียลไทม์", processing: "กำลังประมวลผล...", chapter: "บทที่ {current}", totalChapters: "รวม {total} บท", outline: "โครงร่าง", error: "ข้อผิดพลาด", confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบบันทึกนี้? การดำเนินการนี้ไม่สามารถย้อนกลับได้", confirmDeleteTitle: "ลบบันทึก" }, library: { title: "ห้องสมุดของฉัน", settings: "การตั้งค่า", userInfo: "ข้อมูลผู้ใช้", userId: "รหัสผู้ใช้", booksDir: "ตำแหน่งบันทึกหนังสือ", save: "บันทึก", currentDir: "ตำแหน่งปัจจุบัน", all: "ทั้งหมด", local: "ในเครื่อง", p2p: "แหล่ง P2P", noBooks: "ยังไม่มีหนังสือ ลองสร้างเลย!", read: "อ่าน", delete: "ลบ", chapters: "{count} บท", confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบหนังสือเล่มนี้? ไฟล์ในเครื่องจะถูกลบด้วย ไม่สามารถย้อนกลับได้", confirmDeleteTitle: "ลบหนังสือ", saved: "อัปเดตตำแหน่งบันทึกแล้ว" }, network: { title: "เครือข่าย P2P", myInfo: "ข้อมูลโหนดของฉัน", userId: "รหัสผู้ใช้", ip: "ที่อยู่ IP", bookCount: "จำนวนหนังสือ", nodes: "โหนดออนไลน์", noNodes: "ไม่มีโหนดออนไลน์อื่น", books: "หนังสือที่แชร์", noBooks: "ไม่มีหนังสือที่แชร์", download: "ดาวน์โหลด", downloading: "กำลังดาวน์โหลด...", downloadSuccess: "ดาวน์โหลดหนังสือสำเร็จ!", confirmDownload: "คุณต้องการดาวน์โหลดหนังสือเล่มนี้หรือไม่?", local: "ในเครื่อง", p2p: "P2P" }, reader: { loading: "กำลังโหลด...", notFound: "ไม่พบหนังสือ", back: "กลับไปห้องสมุด" }, modal: { confirm: "ยืนยัน", cancel: "ยกเลิก" } },
  vi: { nav: { generate: "Tạo", history: "Lịch sử", library: "Thư viện", network: "Mạng" }, generate: { title: "Tạo sách điện tử", start: "Bắt đầu tạo", generating: "Đang tạo...", cancel: "Hủy", simple: "Dễ", medium: "Trung bình", hard: "Khó", description: "Mô tả cuốn sách bạn muốn tạo", difficulty: "Độ khó", wordCount: "Số từ mục tiêu", chapterCount: "Số chương", style: "Phong cách", placeholder: "Ví dụ: Sách giới thiệu về trí tuệ nhân tạo cho người mới...", completed: "Tạo xong!", preparing: "Đang chuẩn bị...", error: "Lỗi", cancelled: "Đã hủy", reconnecting: "Đang kết nối lại...", reconnectFailed: "Kết nối lại thất bại", outlinePreview: "Xem trước dàn ý", progress: "Tiến trình tạo", taskRunning: "Nhiệm vụ #{id} · Chuyển trang không làm gián đoạn" }, history: { title: "Lịch sử tạo", newGenerate: "Tạo mới", all: "Tất cả", pending: "Đang xử lý", completed: "Hoàn thành", failed: "Thất bại", deleted: "Đã xóa", noRecords: "Không có lịch sử", goGenerate: "Tạo sách điện tử", viewProgress: "Xem tiến trình", cancel: "Hủy", read: "Đọc", regenerate: "Tạo lại", delete: "Xóa", createdAt: "Ngày tạo", completedAt: "Ngày hoàn thành", difficulty: "Độ khó", wordCount: "Số từ mục tiêu", chapters: "chương", realtimeProgress: "Tiến trình thời gian thực", processing: "Đang xử lý...", chapter: "Chương {current}", totalChapters: "Tổng {total} chương", outline: "Dàn ý", error: "Lỗi", confirmDelete: "Bạn có chắc muốn xóa bản ghi này? Hành động này không thể hoàn tác.", confirmDeleteTitle: "Xóa bản ghi" }, library: { title: "Thư viện của tôi", settings: "Cài đặt", userInfo: "Thông tin người dùng", userId: "ID người dùng", booksDir: "Vị trí lưu sách", save: "Lưu", currentDir: "Vị trí hiện tại", all: "Tất cả", local: "Cục bộ", p2p: "Nguồn P2P", noBooks: "Chưa có sách, hãy tạo một cuốn!", read: "Đọc", delete: "Xóa", chapters: "{count} chương", confirmDelete: "Bạn có chắc muốn xóa cuốn sách này? Tệp cục bộ cũng sẽ bị xóa. Hành động này không thể hoàn tác.", confirmDeleteTitle: "Xóa sách", saved: "Đã cập nhật vị trí lưu" }, network: { title: "Mạng P2P", myInfo: "Thông tin nút của tôi", userId: "ID người dùng", ip: "Địa chỉ IP", bookCount: "Số lượng sách", nodes: "Nút trực tuyến", noNodes: "Không có nút trực tuyến khác", books: "Sách chia sẻ", noBooks: "Không có sách chia sẻ", download: "Tải xuống", downloading: "Đang tải xuống...", downloadSuccess: "Tải sách thành công!", confirmDownload: "Bạn có muốn tải cuốn sách này?", local: "Cục bộ", p2p: "P2P" }, reader: { loading: "Đang tải...", notFound: "Không tìm thấy sách", back: "Quay lại thư viện" }, modal: { confirm: "Xác nhận", cancel: "Hủy" } },
}

// 其余语言映射到相近语言
const aliasMap = {
  'es-419': 'es', 'es-MX': 'es', 'pt-PT': 'pt-BR',
  'ar-EG': 'ar',
}

// 处理别名
for (const [alias, target] of Object.entries(aliasMap)) {
  if (!specific[alias] && specific[target]) {
    specific[alias] = specific[target]
  }
}

// 生成所有语言文件
const outputDir = path.join(__dirname, '../frontend/src/i18n')
const allLangs = { ...languageJson }

for (const [code, name] of Object.entries(allLangs)) {
  // 如果已有独立翻译文件，跳过
  if (specific[code] && typeof specific[code] === 'object' && specific[code].nav) {
    // 写入文件
    const content = JSON.stringify(specific[code], null, 2)
    // 确保格式一致：加上结尾换行
    fs.writeFileSync(path.join(outputDir, `${code}.json`), content + '\n', 'utf-8')
    console.log(`✓ ${code} (${name}) - written`)
    continue
  }
  
  // 如果是别名，复制目标语言
  if (aliasMap[code] && specific[aliasMap[code]]) {
    const content = JSON.stringify(specific[aliasMap[code]], null, 2)
    fs.writeFileSync(path.join(outputDir, `${code}.json`), content + '\n', 'utf-8')
    console.log(`✓ ${code} (${name}) - alias of ${aliasMap[code]}`)
    continue
  }
  
  // 没有翻译的语言，回退到中文
  const content = JSON.stringify(zhCN, null, 2)
  fs.writeFileSync(path.join(outputDir, `${code}.json`), content + '\n', 'utf-8')
  console.log(`✓ ${code} (${name}) - fallback to zh-CN`)
}

console.log('\nDone! All language files generated.')